unicode_syntax: {}

# Import cleanup
imports:
    # Align import names and import lists
    align: true

# Language pragmas
languages_pragmas: {}

# Replace tabs by spaces
tabs:
    # Number of spaces to use for each tab
    spaces: 8

# Remove trailing whitespace
trailing_whitespace: {}
