steps:
  # Convert some ASCII sequences to their Unicode equivalents
  # - unicode_syntax: {}

  # Import cleanup
  - imports:
      # There are different ways we can align names and lists.
      #
      # - global: Align the import names and import list throughout the entire
      #   file.
      #
      # - group: Only align the imports per group (a group is formed by adjacent
      #   import lines).
      #
      # - none: Do not perform any alignment.
      #
      # Default: global.
      align: global

  # Language pragmas
  - language_pragmas:
      # We can generate different styles of language pragma lists.
      #
      # - vertical: Vertical-spaced language pragmas, one per line.
      #
      # - compact: A more compact style.
      #
      # Default: vertical.
      style: vertical

      # stylish-haskell can detect redundancy of some language pragmas. If this
      # is set to true, it will remove those redundant pragmas. Default: true.
      remove_redundant: true

  # Replace tabs by spaces
  - tabs:
      # Number of spaces to use for each tab. Default: 8, as specified by the
      # Haskell report.
      spaces: 8

  # Remove trailing whitespace
  - trailing_whitespace: {}
